// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgdIGJ5Lgr87Z_B87Hl8foE6jqrYnT-Ho',
    appId: '1:502790416083:android:4488004125db7994ef5626',
    messagingSenderId: '502790416083',
    projectId: 'fcm-practice-b4d7c',
    databaseURL: 'https://fcm-practice-b4d7c-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fcm-practice-b4d7c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6xLfLKD1LzC0cP9NX60iUPYc3jP-qg08',
    appId: '1:502790416083:ios:5219d8462f34b141ef5626',
    messagingSenderId: '502790416083',
    projectId: 'fcm-practice-b4d7c',
    databaseURL: 'https://fcm-practice-b4d7c-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fcm-practice-b4d7c.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication3',
  );
}
